[theme]
primaryColor = "#0f766e"
backgroundColor = "#EEEAE3"
secondaryBackgroundColor = "#E6E1D7"
textColor = "#1a1a1a"
font = "sans serif"

[client]
showErrorDetails = true
toolbarMode = "minimal"

[logger]
level = "info"

[server]
maxUploadSize = 200
enableXsrfProtection = true
